apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: feriva22-me-domain-prod
  namespace: istio-system
spec:
  secretName: feriva22-me-domain-prod
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "www.feriva22.me"
  issuerRef:
    name: letsencrypt-feriva22-cluster
    kind: ClusterIssuer
    group: cert-manager.io