apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-feriva22-cluster
  namespace: istio-system
spec:
  acme:
    email: fericodeva69@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory #production letsencrypt
    privateKeySecretRef:
      name: letsencrypt-feriva22-cluster
    solvers:
    - http01:
       ingress:
          class: istio